export class Task {
  APP_RTPath1: string;
  APP_RTPath2: string;
  APP_RTPath3: string;
  ASS_RTPath: string;
  Ar_Amount: number;
  Ar_AmountOLD: number;
  Ar_Approve1: number;
  Ar_Approve2: number;
  Ar_Approve3: number;
  Ar_BranchID: number;
  Ar_Company: string;
  Ar_CusCrTerm: number;
  Ar_CusCrTerm0: number;
  Ar_CusCrTerm2: number;
  Ar_CusCrTerm3: number;
  Ar_CusCrTermOLD: number;
  Ar_CusCrTermOLD0: number;
  Ar_CusCrTermOLD2: number;
  Ar_CusCrTermOLD3: number;
  Ar_CustCT1PayValue: number;
  Ar_CustCT1PayValue_Old: number;
  Ar_CustCT2PayValue: number;
  Ar_CustCT2PayValue_Old: number;
  Ar_EmpName1: string;
  Ar_EmpName2: string;
  Ar_EmpName3: string;
  Ar_EmpParID1: number;
  Ar_EmpParID2: number;
  Ar_EmpParID3: number;
  Ar_UserID1: number;
  Ar_UserID2: number;
  Ar_UserID3: number;
  AssignedBy: number;
  AssignedDate: string;
  AssignedEmpKey: number;
  AssignedName: string;
  AttachFileCount: number;
  CloseByAssign: 0 | 1;
  CommentCount: number;
  HasNotify: number;
  IsCash: 0 | 1;
  REP_RTPath: string;
  ReponsedBy: number;
  ReponsedEmpKey: number;
  ReponsedName: string;
  ReponsedParID: number;
  ResponseDeptID: number;
  StatusEdit: 0 | 1;
  SupportedType: boolean;
  TaskCategory: number;
  TaskCategoryName: string;
  TaskCloseReq: 0 | 1;
  TaskCloserName: string;
  TaskCompleteDate: string;
  TaskCustomerName: string;
  TaskDetail: string;
  TaskDueDate: string;
  TaskDueDateTo: string;
  TaskEditDate: string;
  TaskEmpIDCanCloseJob: number;
  TaskExpectDate: string;
  TaskExpenseType: number;
  TaskFristParentID: number;
  TaskID: number;
  TaskIsCompleted: 0 | 1;
  TaskLevel: number;
  TaskMail_CC: string;
  TaskPVBranchID: number;
  TaskPVBusinessType: number;
  TaskPVCompany: string;
  TaskPVCostCenter: number;
  TaskParentID: number;
  TaskPartyCode: string;
  TaskPartyID: number;
  TaskPercenttage: number;
  TaskPriority: number;
  TaskStartDate: string;
  TaskSubscription: 0 | 1;
  TaskSupplierID: number;
  TaskSupplierName: string;
  TaskSystem: string;
  TaskTag: string;
  TaskTitle: string;
  TaskType: number;
  TaskTypeName: string;
  TaskUserIDEdit: number;
  isPublic: 0 | 1;
}
